default:

  apiDeploy: true

  apis:
    - name: download
    - name: backend

  lambdas: !!files [
    'node_modules/@cumulus/api/config/distribution.yml',
    'node_modules/@cumulus/api/config/api_default.yml'
  ]
