default:
  prefix: test-cumulus-integration
  stackName: '{{prefix}}-iam'

  system_bucket: '{{buckets.internal.name}}'

  useNgapPermissionBoundary: true

  buckets:
    internal:
      name: cumulus-test-sandbox-internal
      type: internal
    private:
      name: cumulus-test-sandbox-private
      type: private
    protected:
      name: cumulus-test-sandbox-protected
      type: protected
    public:
      name: cumulus-test-sandbox-public
      type: public
    protected-2:
      name: cumulus-test-sandbox-protected-2
      type: protected
    shared:
      name: cumulus-data-shared
      type: shared

  params:
     - name: ResourcePrefix
       value: '{{prefix}}'

cumulus-from-npm:
  prefix: test-npm-integration

cumulus-from-source:
  prefix: test-src-integration

cumulus-from-pr:
  prefix: test-pr-integration # used by the PR

cumulus-nightly:
  prefix: nightly # used by the nightly cron job

mhs2:
  prefix: mhs2

  buckets:
    internal:
      name: mhs-internal
      type: internal
    private:
      name: mhs-private
      type: private
    protected:
      name: mhs-protected
      type: protected
    public:
      name: mhs-public
      type: public
    protected-2:
      name: mhs-protected-2
      type: protected
    shared:
      name: cumulus-data-shared
      type: shared

  system_bucket: mhs-internal

aj:
  prefix: aj-integration

aimee-test:
  prefix: aimee-test
  stackName: aimee-test-iam

lf:
  prefix: lf-cumulus
  stackName: lf-cumulus-iam

  buckets:
    internal:
      name: lf-internal
      type: internal
    private:
      name: lf-private
      type: private
    protected:
      name: lf-protected
      type: protected
    public:
      name: lf-cumulus-public
      type: public
    protected-2:
      name: lf-protected-2
      type: protected

lf-int-test:
  prefix: lf-int-test
  stackName: lf-int-test-iam

  buckets:
    internal:
      name: lf-internal
      type: internal
    private:
      name: lf-private
      type: private
    protected:
      name: lf-protected
      type: protected
    public:
      name: lf-cumulus-public
      type: public
    protected-2:
      name: lf-protected-2
      type: protected

lf-sit:
  prefix: lf-sit
  stackName: lf-sit-iam
  useNgapPermissionBoundary: true

  buckets:
    internal:
      name: lf-sit-internal
      type: internal
    private:
      name: lf-sit-private
      type: private
    protected:
      name: lf-sit-protected
      type: protected
    public:
      name: lf-sit-public
      type: public
    protected-2:
      name: lf-sit-protected
      type: protected

jl:
  prefix: jl-test-integration
  buckets:
    private:
      name: jl-test-integration-private
      type: private
    protected:
      name: jl-test-integration-protected
      type: protected
    public:
      name: jl-test-integration-public
      type: public
    protected-2:
      name: jl-test-integration-protected-2
      type: protected
    shared-2:
      name: rvl-internal
      type: shared

kk-uat-deployment:
  prefix: kk-test-uat
  stackName: kk-test-uat-iam
  system_bucket: '{{prefix}}-internal'
  buckets:
    internal:
      name: '{{prefix}}-internal'
      type: internal
    private:
      name: '{{prefix}}-private'
      type: private
    protected:
      name: '{{prefix}}-protected'
      type: protected
    public:
      name: '{{prefix}}-public'
      type: public

mth:
  prefix: mth
  system_bucket: '{{prefix}}-internal'
  buckets:
    internal:
      name: '{{prefix}}-internal'
      type: internal
    private:
      name: '{{prefix}}-private'
      type: private
    protected:
      name: '{{prefix}}-protected'
      type: protected
    public:
      name: '{{prefix}}-public'
      type: public

cum-test:
  prefix: '{{PREFIX}}'
  stackName: '{{PREFIX}}-iam'
  buckets:
    internal:
      name: '{{PREFIX}}-internal'
      type: internal
    protected:
      name: '{{PREFIX}}-protected'
      type: protected
    private:
      name: '{{PREFIX}}-private'
      type: private
    public:
      name: '{{PREFIX}}-public'
      type: public
    shared:
      name: '{{PREFIX}}-data-shared'
      type: shared
    protected-2:
      name: '{{PREFIX}}-protected-2'
      type: protected
  system_bucket: '{{PREFIX}}-internal'

mvd:
  prefix: mvd
  buckets:
    internal:
      name: '{{prefix}}-internal'
      type: internal
  system_bucket: '{{prefix}}-internal'

mvd-dev:
  prefix: mvd-dev
  buckets:
    internal:
      name: 'mvd-internal'
      type: internal
  system_bucket: 'mvd-internal'

jc:
  prefix: jc

mhs:
  prefix: mhs

mhs3:
  prefix: mhs3

jk:
  prefix: jk

jk2:
  prefix: jk2

mboyd-test:
  prefix: mboyd-test
  stackName: mboyd-test-iam

mboyd-int:
  prefix: mboyd-int
  stackName: mboyd-int-iam

pq:
  prefix: pq
